### ISSUE TITLE
Large numbers

### ISSUE THREAD

**Issue by rminderhoud** [nim-lang/c2nim#68] opened 2016-06-13 19:10 UTC
I have the following defined in a header:

`#define MPD_RADIX 10000000000000000000ULL  /* 10**19 */`

c2nim throws the following message:

`Error: number 10000000000000000000 out of valid range`

**Update:**
Seems this can be fixed by manually appending 'u64 when dealing with long long in C header files

**Comment by Araq** [comment] 2021-05-23 22:50
Duplicate of https://github.com/nim-lang/c2nim/issues/93

**Closed by Araq** 2021-05-23 22:50 UTC
