### ISSUE TITLE
failes to parse #if defined without parenthesis

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/c2nim#82] opened 2017-04-09 12:53 UTC
as title, the follow snippet gives an error:

    #if defined a
    #endif

results in `/test.h(2, 5) Error: ';' expected`

parenthesis are not mandatory for `#if defined`

**Comment by Araq** [comment] 2021-05-25 22:08
Duplicate of https://github.com/nim-lang/c2nim/issues/30

**Closed by Araq** 2021-05-25 22:08 UTC
