### ISSUE TITLE
stdint.h types should be translated (int32_t --> int32)

### ISSUE THREAD

**Issue by snej** [nim-lang/c2nim#184] opened 2020-04-22 18:47 UTC
The ubiquitous types declared in <stdint.h> are not translated to their Nim equivalents, so they cause errors errors unless you add your own declarations.

For example, `typedef uint64_t Sequence` is translated to
```
type
  Sequence = uint64_t
```
which results in `Error: undeclared identifier: 'uint64_t'`.

These types include `int8_t, uint8_t, int16_t, uint16_t` ... `uint64_t`.

**Comment by Araq** [comment] 2021-05-30 06:41
Duplicate of https://github.com/nim-lang/c2nim/issues/21

**Closed by Araq** 2021-05-30 06:41 UTC
