### ISSUE TITLE
Converting a .h file fails with "svdpi.h(19, 34) Error: token expected: ;"

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/c2nim#149] opened 2019-01-19 14:32 UTC
Hello,

I was able to build c2nim successfully. 

But when I try to convert this [`svdpi.h`][1] using `c2nim svdpi.h`, I get:
- included in above `svdpi.h`: [`svdpi_compatibility.h`][3]

> svdpi.h(19, 34) Error: token expected: ;

at [this line][2]:

```
typedef unsigned __int64 uint64_t;
```

[1]: https://ptpb.pw/9z4q/c
[2]: https://ptpb.pw/9z4q/c#L-19
[3]: https://ptpb.pw/8La-/c

**Comment by kaushalmodi** [comment] 2019-01-22 19:50
output of nimterop: https://ptpb.pw/-vx0/nim

**Comment by Araq** [comment] 2021-05-23 22:47
Duplicate of https://github.com/nim-lang/c2nim/issues/110

**Closed by Araq** 2021-05-23 22:47 UTC
